medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      pass: admin123
      port: 5432
      dbname: medical_warehouse
      schema: dbt
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 3
      search_path: public
      sslmode: disable
      
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT', 5432) }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt
      threads: 8
      keepalives_idle: 0
      connect_timeout: 30
      retries: 5
      search_path: public
      sslmode: require
